import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className="     flex flex-col h-dvh">

        <Providers>
          <div className="light:bg-gray-100 flex flex-col h-dvh">
            <Header />
            {children}
          </div>

        </Providers>

      </body>

    </html>
  );
}
